apiVersion: batch/v1
kind: Job
metadata:
  name: {{job_name}}
  labels:
    project: {{project_name}}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    spec:
      subdomain: {{job_name}} # has to match Service name
      restartPolicy: Never
      containers:
      - name: sft
        image: {{ container_image }}
        resources:
          limits:
            memory: 32Gi
            cpu: 8
            {% if num_gpu %}
            nvidia.com/gpu: {{ num_gpu }}
            {% else %}
            nvidia.com/gpu: 1
            {% endif %}
        imagePullPolicy: Always
        command:
        - bash
        - "-c"
        {% if num_gpu %}
        - "accelerate launch --config_file /mnt/config/training/distributed.yaml sft.py"
        {% else %}
        - "python sft.py"
        {% endif %}
        env:
        {% if hf_token %}
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{job_name}}
              key: hf_token
        {% endif %}
        {% if wandb_api_key %}
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{job_name}}
              key: wandb_api_key
        - name: WANDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{job_name}}
              key: wandb_username
        - name: WANDB_PROJECT
          value: {{project_name}}
        - name: WANDB_NAME
          value: {{job_name}}
        - name: WANDB_TAGS
          value: {{wandb_tags}}
        - name: WANDB_MODE
          valueFrom:
            secretKeyRef:
              name: {{job_name}}
              key: wandb_mode
        {% endif %}
        {% if s3_endpoint %}
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: {{job_name}}
              key: s3_endpoint
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{job_name}}
              key: s3_access_key_id
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{job_name}}
              key: s3_secret_access_key
        - name: S3_REGION
          valueFrom:
            secretKeyRef:
              name: {{job_name}}
              key: s3_region
        - name: S3_SECURE
          valueFrom:
            secretKeyRef:
              name: {{job_name}}
              key: s3_secure
        {% endif %}

        {% if config_file %}
        volumeMounts:
          - mountPath: "/mnt/config/training"
            name: training-config
            readOnly: true
        {% endif %}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - A100_PCIE_40GB
    {% if config_file %}
      volumes:
        - name: training-config
          configMap:
            name: {{job_name}}
    {% endif %}
