apiVersion: v1
kind: Service
metadata:
  name: {{job_name}}
  labels:
    project: {{project_name}}
spec:
  clusterIP: None # clusterIP must be None to create a headless service
  selector:
    job-name: {{job_name}} # must match Job name